// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeaqdiwfsndzuldmwoqb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlYXFkaXdmc25kenVsZG13b3FiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5ODMyMzMsImV4cCI6MjA2NTU1OTIzM30.T5TWfRdpTr5ijyXTDjL20NbDpBaiK0yM9AaWDhbKa2I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);